import { useEffect, useState, type FormEvent, type MouseEvent, type ReactNode } from 'react';
import { ArrowRight, Check, Clipboard, Crown, LogOut, Shield, Sparkles, Users, X, Zap } from 'lucide-react';
import { approveTeamJoin, approveTeamMerge, createTeam, getServers, getTeams, joinTeam, mergeTeams, previewTeamJoin, verify, type Account, type BossType, type Team, type TeamApplication, type TeamMergeRequest, type TeamRequest } from './api';
import { PlayerSelect } from './PlayerSelect';

const BOSSES = [{ id: 'black-dragon' as const, name: '黑龙', icon: Shield, color: 'violet' }, { id: 'zakum' as const, name: '扎昆', icon: Zap, color: 'orange' }];
const errors: Record<string, string> = { 'account-not-found': '账号信息不匹配，请确认服务器、QQ 和游戏账号', 'team-not-found': '邀请码无效或已过期', 'team-full': '队伍已满（最多 10 人）', 'already-in-team': '该副本今天已经加入其他队伍', 'leader-locked': '你已经是该副本队长，队伍已锁定，不能加入他人队伍', 'already-applied': '已经申请过这个队伍，请等待队长同意', 'request-not-found': '该申请已被处理或已过期', 'merge-target-not-found': '合并目标队伍不存在或已锁定', 'merge-boss-mismatch': '只能合并同一副本、同一服务器的队伍', 'merge-already-applied': '已经向该队伍提交过合并申请', 'merge-request-not-found': '合并申请已处理或已失效', 'not-team-leader': '只有队长可以发起队伍合并', 'server-mismatch': '邀请码所属服务器与当前服务器不一致', 'character-not-owned': '所选角色不属于该账号', 'invalid-input': '请检查输入格式', unauthorized: '验证已过期，请重新进入', 'request-failed': '无法连接服务器，请稍后再试', 'internal-error': '服务器暂时不可用，请稍后再试' };
type Modal = { kind: 'join'; invite: string; boss: string } | { kind: 'approve'; request: TeamRequest; boss: string } | { kind: 'merge'; request: TeamMergeRequest; boss: string } | null;
type CreatePrompt = { bossType: BossType; boss: string; character: string };
const bossName = (boss: BossType) => boss === 'black-dragon' ? '黑龙' : '扎昆';

export default function App() {
  const [token, setToken] = useState(''); const [account, setAccount] = useState<Account | null>(null); const [teams, setTeams] = useState<Team[]>([]); const [applications, setApplications] = useState<TeamApplication[]>([]); const [history, setHistory] = useState<TeamApplication[]>([]);
  const [servers, setServers] = useState<string[]>([]); const [server, setServer] = useState(''); const [qq, setQq] = useState(''); const [gameAccount, setGameAccount] = useState(''); const [day, setDay] = useState(''); const [invite, setInvite] = useState(''); const [joinCharacter, setJoinCharacter] = useState(''); const [modal, setModal] = useState<Modal>(null); const [createPrompt, setCreatePrompt] = useState<CreatePrompt | null>(null); const [message, setMessage] = useState('');
  const [busy, setBusy] = useState(false); const [loadingTeams, setLoadingTeams] = useState(false); const [loadingServers, setLoadingServers] = useState(true); const [serverAttempt, setServerAttempt] = useState(0);
  const showError = (e: unknown) => { const error = e as Error & { code?: string; detail?: string }; setMessage(errors[error.code ?? ''] ?? error.detail ?? '操作失败'); };
  useEffect(() => { setLoadingServers(true); void getServers().then(setServers).catch(showError).finally(() => setLoadingServers(false)); }, [serverAttempt]);
  const refresh = async (authToken: string) => { setLoadingTeams(true); try { const result = await getTeams(authToken); setTeams(result.teams); setApplications(result.applications); setHistory(result.history); setDay(result.day); } finally { setLoadingTeams(false); } };
  const mutate = async (action: () => Promise<unknown>, success: string) => { setBusy(true); setMessage(''); try { await action(); await refresh(token); setMessage(success); } catch (e) { showError(e); } finally { setBusy(false); } };
  const verifyAccount = async (event: FormEvent) => { event.preventDefault(); const normalizedQq = qq.trim(); const normalizedAccount = gameAccount.trim(); if (!servers.includes(server)) return setMessage('请选择有效服务器'); if (!/^\d{5,16}$/.test(normalizedQq)) return setMessage('QQ 请输入 5–16 位数字'); if (!/^[\w-]{1,64}$/.test(normalizedAccount)) return setMessage('游戏账号仅支持字母、数字、下划线和短横线'); setBusy(true); setMessage(''); try { const result = await verify({ server, qq: normalizedQq, gameAccount: normalizedAccount }); setToken(result.token); setAccount(result.account); await refresh(result.token); } catch (e) { showError(e); } finally { setBusy(false); } };
  if (!account) return <Landing servers={servers} loadingServers={loadingServers} server={server} setServer={setServer} qq={qq} setQq={setQq} gameAccount={gameAccount} setGameAccount={setGameAccount} onVerify={verifyAccount} busy={busy} message={message} onRetryServers={() => setServerAttempt((value) => value + 1)} />;
  const joined = new Set(teams.map((team) => team.bossType)); const pending = applications.filter((item) => item.status === 'pending').length;
  const startJoin = async () => { const code = invite.trim().toUpperCase(); if (!/^[A-Z0-9]{6}$/.test(code)) return setMessage('请输入 6 位邀请码'); setBusy(true); setMessage(''); try { const preview = await previewTeamJoin(token, code); setJoinCharacter(account.characters.length === 1 ? account.characters[0] : ''); setModal({ kind: 'join', invite: code, boss: bossName(preview.bossType) }); } catch (e) { showError(e); } finally { setBusy(false); } };
  const confirmJoin = () => { if (!modal || modal.kind !== 'join' || !joinCharacter) return; void mutate(() => joinTeam(token, modal.invite, joinCharacter), '申请已提交，等待队长同意'); setModal(null); setInvite(''); };
  const confirmApprove = () => { if (!modal || modal.kind !== 'approve') return; void mutate(() => approveTeamJoin(token, modal.request.requestId), '已同意玩家入队'); setModal(null); };
  const confirmMerge = () => { if (!modal || modal.kind !== 'merge') return; void mutate(() => approveTeamMerge(token, modal.request.requestId), '已同意合并队伍'); setModal(null); };
  const requestCreate = (boss: typeof BOSSES[number], character: string) => setCreatePrompt({ bossType: boss.id, boss: boss.name, character });
  const confirmCreate = () => { if (!createPrompt) return; void mutate(() => createTeam(token, createPrompt.bossType, createPrompt.character), `${createPrompt.boss} 队伍已创建，邀请码已刷新`); setCreatePrompt(null); };
  return <div className="app"><header className="topbar"><Logo /><div className="player-chip"><span className="online" /><span className="player-name">{account.gameAccount}</span><small>{account.server} · QQ {account.qq}</small><button onClick={() => { setAccount(null); setToken(''); setTeams([]); }} aria-label="退出"><LogOut size={16} /></button></div></header><main className="dashboard"><section className="hero"><div><p className="kicker">PLAYER PARTY HUB</p><h1>组队，<span className="gradient-text">出发</span></h1><p className="hero-copy">申请加入是今天的主流程；创建队伍作为备用入口。</p></div><div className="hero-badge"><Sparkles size={16} /> {day ? `${day} · 北京时间` : '正在同步日期'}</div></section><div className="status-strip"><span><Users size={14} /> 已入队 {teams.length} 个副本</span><span><Sparkles size={14} /> 待审批申请 {pending} 个</span><span className="status-lock"><Check size={14} /> 入队后不可踢出/退出</span></div>
    <JoinCard invite={invite} setInvite={setInvite} disabled={busy} onJoin={startJoin} pending={pending} /><div className="content-grid"><section><div className="section-heading"><div><p className="kicker">CREATE · SECONDARY</p><h2>创建今日队伍</h2></div><span className="capacity">每队最多 10 人</span></div><div className="boss-grid">{BOSSES.map((boss) => <BossCard key={boss.id} boss={boss} joined={joined.has(boss.id)} characters={account.characters} disabled={busy} onCreate={(character) => requestCreate(boss, character)} />)}</div></section><aside><div className="section-heading"><div><p className="kicker">ACTIVE TODAY</p><h2>我的队伍</h2></div><span className="team-count">{teams.length} 个</span></div><div className="team-list">{loadingTeams ? <div className="empty"><Sparkles size={20} /><p>正在加载队伍…</p></div> : teams.length ? teams.map((team) => <TeamCard key={team.inviteCode} team={team} onCopy={() => { navigator.clipboard?.writeText(team.inviteCode); setMessage('邀请码已复制'); }} onApprove={(request) => setModal({ kind: 'approve', request, boss: bossName(team.bossType) })} />) : <div className="empty"><Sparkles size={20} /><p>今天还没有已入队副本</p><small>可以分别报名黑龙和扎昆</small></div>}</div></aside></div><MergeWorkspace teams={teams} disabled={busy} onMerge={(source, target) => void mutate(() => mergeTeams(token, source, target), '合并申请已提交，等待对方队长同意')} onApprove={(request) => setModal({ kind: 'merge', request, boss: bossName(request.bossType) })} /><ApplicationHistory items={history} />{message && <div className="toast">{message}<button onClick={() => setMessage('')} aria-label="关闭提示">×</button></div>}{modal && <ConfirmModal modal={modal} accountName={account.gameAccount} characters={account.characters} character={joinCharacter} setCharacter={setJoinCharacter} busy={busy} onClose={() => setModal(null)} onJoin={confirmJoin} onApprove={confirmApprove} onApproveMerge={confirmMerge} />}{createPrompt && <CreateConfirmModal prompt={createPrompt} busy={busy} onClose={() => setCreatePrompt(null)} onConfirm={confirmCreate} />}</main></div>;
}

function Logo() { return <div className="logo"><span className="logo-orb"><Sparkles size={18} /></span>远征<span className="accent">大厅</span></div>; }
function Landing(p: { servers: string[]; loadingServers: boolean; server: string; setServer: (v: string) => void; qq: string; setQq: (v: string) => void; gameAccount: string; setGameAccount: (v: string) => void; onVerify: (e: FormEvent) => void; busy: boolean; message: string; onRetryServers: () => void }) { return <div className="landing"><header className="topbar"><Logo /><span className="top-note">PLAYER ACCESS</span></header><main className="login-main"><div className="intro"><p className="kicker">MAPLE WORLD · PARTY FINDER</p><h1>一起<span className="gradient-text">组队</span></h1><p>验证账号后，创建或申请加入黑龙、扎昆队伍。</p><div className="raid-pills"><span><Shield size={14} /> 黑龙</span><span><Zap size={14} /> 扎昆</span></div></div><form className="verify-card" onSubmit={p.onVerify}><div className="card-top"><div className="card-icon">✦</div><h2>玩家验证</h2></div><label>服务器<PlayerSelect value={p.server} options={p.servers.map((value) => ({ value, label: value }))} placeholder={p.loadingServers ? '正在加载服务器…' : '选择服务器'} onChange={p.setServer} disabled={p.loadingServers} aria-label="服务器" /></label><label>QQ<input value={p.qq} onChange={(e) => p.setQq(e.target.value)} inputMode="numeric" disabled={p.loadingServers || !p.server} /></label><label>游戏账号<input value={p.gameAccount} onChange={(e) => p.setGameAccount(e.target.value)} disabled={p.loadingServers || !p.server} /></label>{p.message && <div className="form-error" role="alert">{p.message}</div>}<button className="primary" disabled={p.busy || p.loadingServers || !p.server}>{p.busy ? '验证中…' : '进入'}<ArrowRight size={16} /></button>{!p.loadingServers && !p.servers.length && <button type="button" className="secondary" onClick={p.onRetryServers}>重新加载服务器列表</button>}</form></main></div>; }
function BossCard({ boss, joined, characters, disabled, onCreate }: { boss: typeof BOSSES[number]; joined: boolean; characters: string[]; disabled: boolean; onCreate: (character: string) => void }) { const [character, setCharacter] = useState(characters.length === 1 ? characters[0] : ''); const Icon = boss.icon; useEffect(() => { if (characters.length === 1) setCharacter(characters[0]); }, [characters]); const options = characters.map((value) => ({ value, label: `角色 ID ${value}` })); return <div className={`boss-card ${boss.color}`}><div className="boss-art"><Icon size={34} /></div><div className="boss-info"><span className="raid-label">10 PLAYERS · DAILY</span><h3>{boss.name}</h3><p>创建后邀请码仅在今天有效，队长不可关闭队伍</p><div className="card-action">{joined ? <span className="joined"><Check size={14} /> 今日已入队 · 队伍已锁定</span> : <>{characters.length === 1 ? <span className="character-fixed">角色 ID {characters[0]} <Check size={13} /></span> : <PlayerSelect value={character} options={options} onChange={setCharacter} placeholder="选择参与击杀的角色 ID" aria-label={`${boss.name}角色`} disabled={disabled} />}<button disabled={!character || disabled} onClick={() => onCreate(character)}>锁定并创建 <ArrowRight size={14} /></button></>}</div></div></div>; }
function JoinCard(p: { invite: string; setInvite: (value: string) => void; disabled: boolean; onJoin: () => void; pending: number }) { return <div className="join-card join-card-primary"><div className="join-icon"><Users size={22} /></div><div className="join-copy"><span className="raid-label">PRIMARY ACTION · APPLY</span><h3>申请加入队伍</h3><p>{p.pending ? `已有 ${p.pending} 个申请等待队长同意` : '输入邀请码后选择角色，队长确认后正式入队'}</p></div><div className="join-controls"><input value={p.invite} onChange={(e) => p.setInvite(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g, ''))} maxLength={6} placeholder="6 位邀请码" aria-label="6 位邀请码" /><button disabled={!/^[A-Z0-9]{6}$/.test(p.invite) || p.disabled} onClick={p.onJoin}>下一步 <ArrowRight size={14} /></button></div></div>; }
function TeamCard({ team, onCopy, onApprove }: { team: Team; onCopy: () => void; onApprove: (request: TeamRequest) => void }) { return <div className="team-card"><div className="team-card-head"><span className={`boss-dot ${team.bossType}`} /><strong>{bossName(team.bossType)}</strong>{team.leader && <span className="leader-tag"><Crown size={11} /> 队长 · 已锁定</span>}<span className="member-total"><Users size={13} />{team.members.length}/10</span></div><div className="member-list">{team.members.map((member) => <span key={member.characterId} className={member.isLeader ? 'leader' : ''}>{member.characterId}</span>)}</div>{team.leader && team.pendingRequests?.length ? <div className="pending-box"><small>待你确认的入队申请</small>{team.pendingRequests.map((request) => <div className="pending-row" key={request.requestId}><span>{request.gameAccount} · 角色 ID {request.characterId}</span><button onClick={() => onApprove(request)} disabled={team.members.length >= 10}>同意</button></div>)}</div> : null}<div className="invite-row"><small>今日邀请码</small><b>{team.inviteCode}</b><button onClick={onCopy} aria-label="复制邀请码"><Clipboard size={14} /></button></div></div>; }
function MergeWorkspace({ teams, disabled, onMerge, onApprove }: { teams: Team[]; disabled: boolean; onMerge: (source: string, target: string) => void; onApprove: (request: TeamMergeRequest) => void }) { const leaders = teams.filter((team) => team.leader); if (!leaders.length) return null; return <section className="merge-workspace"><div className="section-heading"><div><p className="kicker">LEADER ONLY</p><h2>合并队伍</h2></div><span className="capacity">同副本 · 合计不超过 10 人</span></div>{leaders.map((team) => <MergeTeamRow key={team.inviteCode} team={team} disabled={disabled} onMerge={onMerge} onApprove={onApprove} />)}</section>; }
function MergeTeamRow({ team, disabled, onMerge, onApprove }: { team: Team; disabled: boolean; onMerge: (source: string, target: string) => void; onApprove: (request: TeamMergeRequest) => void }) { const [target, setTarget] = useState(''); return <div className="merge-row"><div><strong>{bossName(team.bossType)}队伍</strong><small>当前 {team.members.length}/10 人 · 你的邀请码 {team.inviteCode}</small></div><div className="merge-form"><input value={target} onChange={(e) => setTarget(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g, ''))} maxLength={6} placeholder="输入对方队伍邀请码" aria-label="合并目标队伍邀请码" /><button disabled={disabled || !/^[A-Z0-9]{6}$/.test(target)} onClick={() => { onMerge(team.inviteCode, target); setTarget(''); }}>申请合并</button></div>{team.pendingMergeRequests?.map((request) => <div className="merge-request" key={request.requestId}><span>来自 {request.sourceInviteCode} 的整队申请 · {request.memberCount} 人</span><button disabled={disabled || team.members.length + request.memberCount > 10} onClick={() => onApprove(request)}>查看并同意</button></div>)}</div>; }
function ApplicationHistory({ items }: { items: TeamApplication[] }) { if (!items.length) return null; return <details className="application-history"><summary><span className="kicker">JOIN HISTORY</span><small>最近 50 条 · 点击展开</small></summary><div className="history-list">{items.slice(0, 6).map((item) => <div className="history-row" key={item.requestId}><span><b>{bossName(item.bossType)}</b> · 角色 ID {item.characterId}<small>{item.day}</small></span><em className={`application-status ${item.status}`}>{item.status === 'approved' ? '已同意' : item.status === 'pending' ? '待队长' : '未通过'}</em></div>)}</div></details>; }
function CreateConfirmModal({ prompt, busy, onClose, onConfirm }: { prompt: CreatePrompt; busy: boolean; onClose: () => void; onConfirm: () => void }) { return <ModalShell title={`确认创建${prompt.boss}队伍`} kicker="CREATE TEAM" close={onClose} onBackdrop={(event) => { if (event.target === event.currentTarget) onClose(); }}><div className="raid-confirm"><span className={`boss-dot ${prompt.bossType}`} />副本：<b>{prompt.boss}</b><small>角色 ID {prompt.character}</small></div><p className="modal-copy">确认使用角色 ID <b>{prompt.character}</b> 成为本队队长吗？</p><div className="warning"><Shield size={16} />创建后队伍今日锁定，不能关闭；队长不能加入同副本的其他队伍，成员入队后也不能退出。</div><button className="primary" disabled={busy} onClick={onConfirm}>确认锁定并创建</button><button className="secondary modal-cancel" onClick={onClose}>返回修改</button></ModalShell>; }
function ConfirmModal(p: { modal: Exclude<Modal, null>; accountName: string; characters: string[]; character: string; setCharacter: (value: string) => void; busy: boolean; onClose: () => void; onJoin: () => void; onApprove: () => void; onApproveMerge: () => void }) { const options = p.characters.map((value) => ({ value, label: `角色 ID ${value} · ${p.accountName}` })); const close = (event: MouseEvent<HTMLDivElement>) => { if (event.target === event.currentTarget) p.onClose(); }; if (p.modal.kind === 'join') return <ModalShell title={`确认申请加入${p.modal.boss}队伍`} kicker="FINAL STEP" close={p.onClose} onBackdrop={close}><div className="raid-confirm"><span className={`boss-dot ${p.modal.boss === '黑龙' ? 'black-dragon' : 'zakum'}`} />副本：<b>{p.modal.boss}</b><small>邀请码 {p.modal.invite}</small></div><p className="modal-copy">请选择真正参与击杀的角色 ID（账号：{p.accountName}）：</p>{p.characters.length === 1 ? <div className="character-fixed modal-character">角色 ID {p.characters[0]} · {p.accountName} <Check size={14} /></div> : <PlayerSelect value={p.character} options={options} onChange={p.setCharacter} placeholder="选择参与击杀的角色 ID" aria-label="参与击杀角色 ID" disabled={p.busy} />}<div className="warning"><Shield size={16} />加入后今日不可退出；一个角色只能领取一次奖励，角色 ID 错误将无法获得奖励。</div><button className="primary" disabled={!p.character || p.busy} onClick={p.onJoin}>确认申请</button><button className="secondary modal-cancel" onClick={p.onClose}>返回</button></ModalShell>; if (p.modal.kind === 'approve') return <ModalShell title={`同意 ${p.modal.request.gameAccount} 入队`} kicker="LEADER APPROVAL" close={p.onClose} onBackdrop={close}><p className="modal-copy">申请角色：<b>{p.modal.request.characterId}</b>。同意后将正式入队。</p><div className="warning"><Shield size={16} />同意入队后今日不可踢出，请确认玩家与角色确实参与本次击杀。</div><button className="primary" disabled={p.busy} onClick={p.onApprove}>确认同意入队</button><button className="secondary modal-cancel" onClick={p.onClose}>返回</button></ModalShell>; return <ModalShell title={`确认合并${p.modal.boss}队伍`} kicker="LEADER APPROVAL" close={p.onClose} onBackdrop={close}><p className="modal-copy">对方会将整队成员一次性加入你的队伍，共 <b>{p.modal.request.memberCount} 人</b>。</p><div className="warning"><Shield size={16} />合并后原队伍将锁定并失效，所有成员进入当前队伍；请确认总人数不超过 10 人。</div><button className="primary" disabled={p.busy} onClick={p.onApproveMerge}>确认合并队伍</button><button className="secondary modal-cancel" onClick={p.onClose}>返回</button></ModalShell>; }
function ModalShell(p: { title: string; kicker: string; close: () => void; onBackdrop: (event: MouseEvent<HTMLDivElement>) => void; children: ReactNode }) { return <div className="modal-backdrop" role="presentation" onMouseDown={p.onBackdrop}><section className="confirm-modal" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><button className="modal-close" onClick={p.close} aria-label="关闭"><X size={18} /></button><p className="kicker">{p.kicker}</p><h2 id="confirm-title">{p.title}</h2>{p.children}</section></div>; }
