import { Check, X } from 'lucide-react';
import { useEffect, useState, type FormEvent } from 'react';
import type { ServerRecord } from '../../api/types';

export interface ServerFormValue { id: string; name: string; address: string; version: string; map_id: string; enabled: boolean; spawn_rate: number; exp_rate: number; exp_max: number; drop_rate: number; meso_rate: number; domain_times: number }
const quickFields = [['spawn_rate', '怪物数量倍率'], ['exp_rate', '经验倍率'], ['exp_max', '持续分钟数'], ['drop_rate', '掉落倍率'], ['meso_rate', '金币倍率'], ['domain_times', '副本次数']] as const;
export function ServerFormDialog({ server, onClose, onSave }: { server?: ServerRecord; onClose: () => void; onSave: (value: ServerFormValue) => Promise<boolean> }) {
  const [form, setForm] = useState<ServerFormValue>({ id: server?.id ?? '', name: server?.name ?? '', address: server?.address ?? '127.0.0.1:12660', version: server?.version ?? '1.0.2', map_id: server?.map_id ?? '211000000', enabled: server?.enabled ?? true, spawn_rate: server?.spawn_rate ?? 2, exp_rate: server?.exp_rate ?? 13, exp_max: server?.exp_max ?? 99999999, drop_rate: server?.drop_rate ?? 3, meso_rate: server?.meso_rate ?? 5, domain_times: server?.domain_times ?? 2 });
  const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === 'Escape' && !saving) onClose(); }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, [onClose, saving]);
  const update = (key: keyof ServerFormValue, value: string | number | boolean) => { setForm((current) => ({ ...current, [key]: value })); setError(''); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!server && !/^[a-z0-9][a-z0-9-]{0,63}$/u.test(form.id.trim())) return setError('Use lowercase letters, numbers, and hyphens for the ID'); if (!form.name.trim() || !form.address.trim() || !form.version.trim() || !form.map_id.trim()) return setError('Complete the server fields'); if ([form.spawn_rate, form.exp_rate, form.exp_max, form.drop_rate, form.meso_rate, form.domain_times].some((value) => !Number.isInteger(value) || value < 1)) return setError('Quick command values must be positive integers'); setSaving(true); try { if (await onSave({ ...form, id: form.id.trim(), name: form.name.trim(), address: form.address.trim(), version: form.version.trim(), map_id: form.map_id.trim() })) return; setError('Save failed'); } finally { setSaving(false); } };
  return <div className="management-dialog-scrim" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !saving) onClose(); }}><section className="management-dialog" role="dialog" aria-modal="true" aria-labelledby="server-form-title"><header className="management-dialog-heading"><h2 id="server-form-title">{server ? 'Edit server' : 'Add server'}</h2><button type="button" className="icon-button" aria-label="Close" onClick={onClose} disabled={saving}><X size={18} /></button></header><form className="management-form" onSubmit={submit}><label><span>Server ID</span><input required disabled={Boolean(server) || saving} value={form.id} onChange={(event) => update('id', event.target.value)} /></label><label><span>Name</span><input required disabled={saving} value={form.name} onChange={(event) => update('name', event.target.value)} /></label><label><span>Address</span><input required disabled={saving} value={form.address} placeholder="127.0.0.1:12660" onChange={(event) => update('address', event.target.value)} /></label><div className="management-form-grid"><label><span>Version</span><input required disabled={saving} value={form.version} onChange={(event) => update('version', event.target.value)} /></label><label><span>Map ID</span><input required disabled={saving} value={form.map_id} onChange={(event) => update('map_id', event.target.value)} /></label></div><fieldset><legend>快捷指令配置</legend><div className="management-form-grid">{quickFields.map(([key, label]) => <label key={key}><span>{label}</span><input type="number" min="1" step="1" disabled={saving} value={form[key]} onChange={(event) => update(key, Number(event.target.value))} /></label>)}</div></fieldset><label className="management-checkbox"><input type="checkbox" disabled={saving} checked={form.enabled} onChange={(event) => update('enabled', event.target.checked)} /><span>Enable server</span></label>{error && <p className="management-form-error" role="alert">{error}</p>}<div className="management-dialog-actions"><button type="button" className="secondary-button" onClick={onClose} disabled={saving}>Cancel</button><button type="submit" className="primary-button" disabled={saving}>{saving ? 'Saving…' : <><Check size={16} />Save</>}</button></div></form></section></div>;
}